# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/dark.css"
locale: en-US
title: "Danger From Deer"
description: 'The Deer... They are coming!'
baseurl: / # the subpath of your site, e.g. "/blog"
# url: 'https://dangerfromdeer.com'
url: 'https://mcgodfrey.github.io'
logo: "/img/2016/01/cropped-finished-product-300x300.jpg" # path of site logo, e.g. "/images/logo.png"
date_format: "%Y-%m-%d"
# date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:year/:month/:day/:title:output_ext

markdown: kramdown

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false

# Site Author
author:
  name: Matt
  # picture:
  # email:
  # twitter:
  # links:
  #   - title:
  #     url:
  #     icon:

# Footer Links
# footer_links:
#   - title: Feed
#     url: atom.xml
#     icon: fas fa-rss-square


